export default [
  {
    id: 1,
    question:
      "The young Jedi Knight, Anakin Skywalker, becomes who in Star Wars?",
    answer: "Darth Vader",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 2,
    question: "The planet Kashyyyk is home to who?",
    answer: "Chewbacca and the Wookiees",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 3,
    question:
      "In Revenge of the Sith and Attack of the Clones what color is Yoda’s lightsaber?",
    answer: "Green",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 4,
    question: "The X-wing fighter has how many engines?",
    answer: "Four",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 5,
    question: "Jedi Council consists of how many members?",
    answer: "12",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 6,
    question: "What were Luke’s aunt and uncle’s jobs on Tatooine?",
    answer: "Moisture farmers",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 7,
    question: "How many languages is C-3P0 fluent in?",
    answer: "Over 6 million",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 8,
    question: "Which character is partially named after George Lucas’ son?",
    answer: "Dexter Jettster",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 9,
    question:
      "How many Dewbacks were in the original 1977 theatrical cut of the first Star Wars movies?",
    answer: "Two",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 10,
    question: "What color is Mace Windu’s lightsaber?",
    answer: "Purple",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 11,
    question: "Who played the part of Mace Windu?",
    answer: "Samuel L. Jackson",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 12,
    question: "Which species stole the plans to the death star?",
    answer: "Bothans",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 13,
    question:
      "What kind of trooper is introduced at the beginning of Rogue One?",
    answer: "Death Troopers",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 14,
    question: "Who kissed Leia first, Han or Luke?",
    answer: "Luke",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 15,
    question: "What does AT-AT stand for?",
    answer: "All Terrain Armored Transport",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 16,
    question:
      "What odds does C-3P0 give Han for successfully navigating the asteroid field?",
    answer: "3,720 to 1",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 17,
    question:
      "Who are the masters of the Dark Side that want to rule the galaxy?",
    answer: "The Sith",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 18,
    question: "Count Dooku is also known as who?",
    answer: "Darth Tyranus",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 19,
    question: "What is the name of Boba Fett’s ship?",
    answer: "Slave 1",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 20,
    question: "Who was the original commander of the Death Star?",
    answer: "Grand Moff Tarkin",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 21,
    question: "What was the name of the planet that the clones were made on?",
    answer: "Kamino",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 22,
    question: "What is the largest annual podrace in the world?",
    answer: "The Boonta Eve Classic",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 23,
    question:
      "When Leia, first tells Han Solo that she loves him, what is his reply?",
    answer: "“I know.”",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 24,
    question: "What day is Wookiee Life Day?",
    answer: "November 17th",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 25,
    question:
      "Peter Mayhew played the part of who in the original Star Wars Trilogy?",
    answer: "Chewbacca",
    answerShown: false,
    difficulty: "easy",
  },
  {
    id: 26,
    question:
      "What language are the words written on Darth Vader’s chest piece in?",
    answer: "Ancient Hebrew",
    answerShown: false,
    difficulty: "hard",
  },
  {
    id: 27,
    question: "What is the other name for The Imperial Probe Droid?",
    answer: "Probot",
    answerShown: false,
    difficulty: "medium",
  },
  {
    id: 28,
    question:
      "The four Jedi Masters Kit Fisto, Mace Windu, Agen Kolar, and Saesee Tinn, were killed by who?",
    answer: "Darth Sidious",
    answerShown: false,
    difficulty: "medium",
  },
];
